### ISSUE TITLE
HTML load time

### ISSUE THREAD

**Issue by agitter** [greenelab/covid19-review#1015]
The HTML for the complete manuscript https://greenelab.github.io/covid19-review/ has gotten quite slow to load.  This came up as an issue during manuscript review (#1014).

The Chrome performance tool shows it takes about 40s to load on my machine
![image](https://user-images.githubusercontent.com/3532898/131147629-648d66a6-f68d-497c-8f03-c8c5abc3d067.png)

@vincerubinetti do you have any ideas about how to optimize load times?  Would it help if we collapse the appendix?  Disable scite  by default?  The javascript elements, like showing citation information on hover, can also be unresponsive in this huge manuscript.

**Comment by agitter** [comment]
A recent HTML artifact took 54.55s in my browser:
[manuscript-1.0.4455-ee85f29.html.txt](https://github.com/greenelab/covid19-review/files/7150156/manuscript-1.0.4455-ee85f29.html.txt)

Hiding the references with `style="display: none"` did speed up loading considerably to 28.08s:
[manuscript-1.0.4455-ee85f29-collapse-refs.html.txt](https://github.com/greenelab/covid19-review/files/7150169/manuscript-1.0.4455-ee85f29-collapse-refs.html.txt)

Disabling scite also provided a big boost with a load time of 32.69s:
[manuscript-1.0.4455-ee85f29-no-scite.html.txt](https://github.com/greenelab/covid19-review/files/7150170/manuscript-1.0.4455-ee85f29-no-scite.html.txt)

These times could be skewed because I didn't have the images directory locally.  The trends are still informative.  @rando2 what do you think of the HTML load time issues?  We describe scite integration as one of the new features of Manubot that was useful for this review, but is it worth substantially slower load times?

It would be nice to provide a way to optionally load the scite badges only when the reader requests them.  That seems conceptually possible to me, but I don't know how to implement it and we won't have it before the DISCO submission deadline.  Perhaps we mention that as a limitation and possible future work?

(I added `.txt` as a suffix to all the `.html` files.  Remove the `.txt` to test this localy.)

**Comment by domenicrosati** [comment]
Hey there! hope I am not intruding here, but just to chime in from scite (where I work). 

The badges are designed to all load asynchronously and not interfere with page loading (unless you mean until everything is finished loading in the network requests and the badges are finished loading? is this what you mean?).

I had a look and I don't see how disabling them would provide a better load time... so if you had any more details on this I'd love to work on trying to make badge loading faster or interfere less (though it really shouldn't interfere with loading at all...) Are the badges blocking any of your requests or rendering?

**Comment by vincerubinetti** [comment]
@domenicrosati They're using "loading" in the colloquial sense; what's really being slow is the page rendering and painting. Each badge is taking a negligible time to load/render/paint/etc, but there are 1500 of them (an extreme that I'm guessing you haven't encountered yet) and it is adding up.

@agitter I'll come up with an IntersectionObserver snippet that you can insert to see if that helps. Regarding collapsing, you'll want to apply the `data-collapsed="true"` attribute to the `<h2>` before the `<div id="refs">` element. I believe that should be possible using the `attribute` plugin like `## References <!-- $data-collapsed="true" -->`. However, because of the way the `accordion` plugin works, it'll override this on load; I'll have to make a modification to it. Alternatively, you could set the `accordion` plugin to just always collapse everything by default. That may be understandable to the user for a manuscript of this magnitude. 

I'll do a PR for these changes.

**Comment by rando2** [comment]
Thank you @vincerubinetti!
And @domenicrosati happy to have you here whenever you feel like popping over! I hope we can be an interesting use case with our absurd number of references 😆

**Comment by agitter** [comment]
> They're using "loading" in the colloquial sense; what's really being slow is the page rendering and painting.

Yes, thanks for being more precise about this.

> Alternatively, you could set the accordion plugin to just always collapse everything by default. That may be understandable to the user for a manuscript of this magnitude.

Collapsing everything by default could be a good option.  Or at least we could collapse all of the appendices.  The Mount Sinai reviews must take a long time to render, and they are not too pertinent.

@rando2 do you have an opinion about collapsing all of the HTML sections versus only the appendices or appendices and references?
