### ISSUE TITLE
Static figure not rendering in HTML (but are in PDF)

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#1128]
**Is your feature request related to a problem? Please describe.**

In reviewing #1115, @ajlee21 noticed that Figure 6, which is just a jpg in the images directory, does not render in the HTML build. Only the caption appears, although that does seem to be formatted correctly.

**Describe the solution you'd like**

This could be related to #1015? Or something else

**Describe alternatives you've considered**

I feel like we might have discussed this at some point but I couldn't find it in the issues

**Additional context**
HTML:
![Screen Shot 2022-04-14 at 10 18 46 AM](https://user-images.githubusercontent.com/8975841/163410057-1afb2e26-fdc2-48f3-9dbc-9e5a264b61ff.png)

PDF:
![Screen Shot 2022-04-14 at 9 57 10 AM](https://user-images.githubusercontent.com/8975841/163410093-039a88cc-c5b3-4869-b938-1c8c0ecfbe9a.png)

@agitter

**Comment by agitter** [comment]
I don't think there is a problem.  This is an expected annoyance of reviewing the HTML artifacts from a GitHub or AppVeyor build.  The artifact doesn't include a copy of the local images, so the HTML file shows a missing image thumbnail.  The remote images that are specified by URL still appear because they are being fetched from the remote site.  The same problem affects the ORCID, GitHub, and Twitter images in the author list.

The main HTML document and the PDF and DOCX artifacts in #1115 have the figure, so everything looks okay to me.

**Comment by rando2** [comment]
Wonderful, thank you so much @agitter! That's great news.

**Comment by ajlee21** [comment]
Thank you both for checking!
