### ISSUE TITLE
Strategies for Systematic Review

### ISSUE THREAD

**Issue by juliettemarie0405** [greenelab/covid19-review#13]
Hi all,

So excited that you are starting this initiative and very grateful to be involved! I was involved in a systematic review a couple years ago. Based on that experience, I have some thoughts/questions outlined below.

1. **Centralized database.** In order to synthesize the data we garner from the literature, wouldn't it be helpful to have information on each paper stored in a data format that is able to be searched and sorted? Is it possible to make a collaborative excel sheet on GitHub? That way we could list the paper information, name of the individual reviewing, whether it contains information relevant to diagnosis/therapeutics/other, the area of study (virology vs. epidemiology etc.), the summary of findings, and whatever other information we deem important. We would then have a centralized database that can be sorted and searched for relevant information when writing up the paper.

2. **Inclusion and Exclusion Criteria**. The typical systematic review process (from my experience) starts with an initial scan of titles and abstracts based on pre-specified inclusion and exclusion criteria. Those deemed relevant in that first pass are then subjected to a full-text scan based on another set of pre-specified inclusion and exclusion criteria. The resulting set of relevant papers are then subjected to data extraction. I think it might be important to get area experts involved in designing these inclusion and exclusion criteria. The literature at hand encompasses so many different topics that we would need help identifying those relevant to therapeutics and diagnostics (for example, do we want to include papers that estimate the reproduction number? or model the global spread of the pandemic? or are these questions beyond the scope of therapeutics/diagnostics?) Once we have these inclusion/exclusion criteria in place, we could crowd-source for help in the first and second pass scans of the literature.

In my experience, these scans of the literature are always done by hand, usually by two independent reviewers who talk through any discrepancies. When I was involved in this process, we used a software called [EROS](http://eros-systematic-review.org/) (but the link no longer seems to work...so it may not exist anymore?). Perhaps it would be possible to do this with machine learning? The main roadblock I can foresee is that abstracts and full-texts will include references to previous literature, so it would be difficult for a non-human to identify what the **primary data** from each paper is.

3. **Risk of Bias**. Typical systematic reviews also include a Risk of Bias assessment, in which each paper included in the review is assessed based on a pre-specified set of criteria (ex. Is there a control group? Were researchers blinded to experimental conditions?). Performing such a review informs how well we can trust the results of each study. The relevant criteria for performing a Risk of Bias assessment will vary depending on the type of study, however. For example, I can imagine that the sources of bias for a study coming from a virology lab performing a randomized control trial with cell lines will be vastly different from an epidemiological study attempting to estimate the reproduction number. Could we recruit experts in each area to design risk of bias assessment tools so we can understand the quality of data we collect?

4. **New Articles** How would we ensure we are including all new publications? In systematic reviews, you develop a search strategy using a combination of keywords and synonyms, and then input that search strategy into several different databases (such a PubMed, Web of Science, etc.). For most databases you can sign up to receive alerts when new articles are published that meet your search criteria. Would we set something like this up?

Thinking about all of this, I wonder if getting a reference librarian involved would be a good idea. I have heard of a terrific librarian from the Biomedical library at UPenn who is the go-to expert on systematic reviews. Perhaps she would be willing to be involved!

@rando2 @cgreene

**Comment by rando2** [comment]
Hi @juliettemarie0405 ,
Thank you so much for putting together these thorough suggestions! It will be so valuable to have you involved given your experience with conducting systematic reviews!

Given how fast-moving the literature in this field is, it unfortunately seems unlikely that we'll be able to pull off a formal systematic review, but we would like this to be an "as good as possible" review. There are a lot of points in your issue that point to ways to organize things to make sure people are getting involved where they're most needed and finding tasks that fit their skill sets. Speaking with Casey (who has a lot of experience with collaborative reviews like this where it's more open-ended who is involved at any time), it seems like we might want to try add some of the structures you suggested, while still relying on some of GitHub's strengths.

Based on your suggestions and Casey's concerns about these challenges, I think it might make sense to take the following steps:
1. Casey thinks maintaining a database might be a little tricky, and if we start, we won't be able to abandon it if it isn't working well. However, he said that he's had good success with the search features in the Issues. I think we can use an issue-based approach to form sort of a database, although it won't be in the grid format the we're used to seeing. If this doesn't work, we can move to a different format as we figure out what does and doesn't work!

2. Based on your concerns, I think we should modify the [current template](https://raw.githubusercontent.com/greenelab/covid19-review/master/.github/ISSUE_TEMPLATE/new-paper-template.md) so people can explicitly specify the fields the paper touches on (like you noted), e.g.,:
- [ ] Virology
- [ ] Epidemiology
- [ ] Medicine
- [ ] Molecular biology
- [ ] Pharmacology
... any others to add to that list @juliettemarie0405 ? 
Technical note to @cgreene -- I'm new to CI but do you think it might be possible to trigger auto-labeling based on regular expressions (e.g., r"[x] Epidemiology")? I found [this](https://github.com/tonglil/labeler) but am unclear on how adaptable it is. Otherwise we should reframe and have people delete any of the words that aren't relevant so we can rely on the native Issues search function.

2. I think it would be great to have you or someone else with a relevant background do an abstract/title review like you described, but what if instead of an explicit inclusion/exclusion criteria, you opened an issue for each paper and then determine whether you think they are relevant/not relevant (or high, medium, low priority) based on what we know right now? That way, if something changes later on as more info emerges and we find out something random and unexpected is actually very important, we can go back through all the excluded papers you looked at and reassess their relevance.

3. To help with the above, it would be great to get a rough outline of what topics we think the paper should include. We've already started an outline for the [intro](https://github.com/greenelab/covid19-review/pull/11) and [body](https://github.com/greenelab/covid19-review/pull/12), but we would love your and Ronnie's feedback on where you think these should go. As a note, there are currently outstanding edits I need to incorporate, so those links will let you see the proposed changes as we work on them.

4. Risk of Bias: As you mentioned when we spoke, different contributors, especially across fields, will likely have different understandings of the bias or limitations of each study. I tried to leave it open ended in the [current template](https://raw.githubusercontent.com/greenelab/covid19-review/master/.github/ISSUE_TEMPLATE/new-paper-template.md). Are there different or better questions we should ask to help us assess risk of bias? Because this will be such a decentralized process, it would be great if we could keep thinking about this and editing the information we collect to try to stay on top of it.  Do we need more questions on this topic?

4. For new articles, our main plan was to rely on contributors to add things as they find them. You're right that it would be a good idea to set up some alerts. If you have any suggestions for how to approach this based on your experience, they would be very much appreciated! I'm not sure if they're updating the [Kaggle dataset list](https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge/tasks), but I'll also keep an eye on that.

Please let me know what you think and thank you so much for raising such thoughtful questions! I'm so thankful that you are involved!

**Comment by cgreene** [comment]
> Technical note to @cgreene -- I'm new to CI but do you think it might be possible to trigger auto-labeling based on regular expressions (e.g., r"[x] Epidemiology")? I found this but am unclear on how adaptable it is. Otherwise we should reframe and have people delete any of the words that aren't relevant so we can rely on the native Issues search function.

What do you think about having an issue template for each of those with a catch-all for those that don't fit into a category? I think @SiminaB mentioned something like this in #6 as well.

If there is a regexp-based labeler that's built into GitHub Actions, that'd be the way to go. I'm not sure if there is one though.

**Comment by cgreene** [comment]
Ok! I have added automatic labeling. Here's an example. I think the best way to use it would be to have a template with the boxes _unchecked_, and then to have the regexp search for checked boxes. The regular expressions are defined here: https://github.com/greenelab/covid19-review/blob/master/.github/labeler.yml

![Screen Shot 2020-03-23 at 4 31 34 PM](https://user-images.githubusercontent.com/542643/77360496-d3a04380-6d23-11ea-9e6d-21d2a61463ed.png)

I was optimistic in #25. It also took #26 and #28 but at least I got to file https://github.com/github/issue-labeler/pull/6

**Comment by rando2** [comment]
This is so awesome, @cgreene ! I'll try to brainstorm a few more tags to add tomorrow. So excited about this feature!

**Comment by agitter** [comment]
The [CiteNet](https://citenet.io/) search tool could provide another way to discover relevant papers.  It indexes bioRxiv and medRxiv and uses semantic search.  They have a [COVID-19 demo](https://vectorinstitute.ai/2020/03/20/vector-researchers-release-scientific-paper-search-tool-to-help-in-fight-against-covid-19/).

No need to re-open the issue.
