### ISSUE TITLE
Add COI and CRediT info to contribution metadata template format

### ISSUE THREAD

**Issue by mprobson** [greenelab/covid19-review#18]
This repo requires conflict of interest disclosure (COI) to be added to the metadata file for a new author entry but the template format is not specified in the linked file.

Additionally, the contribution section does not make note of the fact that it should be one of the fourteen CredIT taxonomy roles found here: https://casrai.org/credit/

Possible solutions include pointing the template format at something other than the rootstock default since this is repo specific or including extra directions and links in the main README.md file. Alternatively, a CONTRIBUTING.md file could describe this process in greater detail (and be linked to from the main page). More info on CONTRIBUTING files and there use in software projects on GitHub can be found here: https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors . I would be happy to help author any/all of these documents or changes.

Thanks again for putting this all together and welcoming so many people!

**Comment by cgreene** [comment]
I agree that adding this information in our USAGE.md document and directly linking to how to add oneself as an author as part of the first pull request with content would be great to have in the README.md file.

I think that you can propose a PR here that will include this information:
https://github.com/greenelab/covid19-review/blob/master/USAGE.md#manuscript-metadata

I wanted to get the COI because it may be pertinent for some contributors and it'll make things more straightforward when this gets submitted to a journal. For a past review we had to go back to everyone for the information. We may still need to do that, but now they'll just have to update the dates. Thanks!

**Comment by cgreene** [comment]
Oh, and the CRediT taxonomy mention would be great too! I've not used it before and it doesn't look _perfect_ for a review, but it'll be helpful to have folks contribution types captured when we have to make author ordering decisions.
