### ISSUE TITLE
Inconsistent Style and Terminology

### ISSUE THREAD

**Issue by matfax** [greenelab/covid19-review#258]
**Is your feature request related to a problem? Please describe.**
Participating authors seem to be free to use different terms and writing styles at the moment. This might become confusing for the reader. For instance, some authors write "anti-viral", others write "antiviral". Both terms are correct. But the reader might become confused in such a huge document if there are multiple terms with the same definition. New authors also might get confused when they want to reuse already introduced terms. Also, it's not comfortable to read a document with different writing styles. Journals normally set standardized writing guidelines for new applications.

**Describe the solution you'd like**
More consensus finding could be integrated in the participation process. The currently participating authors could agree on an existing standardized writing style that provides detailed guidelines and examples for corner cases. Some of the writing and style checks could also be integrated in automated or semi-automated GitHub PR checking. A terminology appendix could be added to the paper so that terms are consistently defined for reuse.

**Describe alternatives you've considered**
Definitions could also be managed as issues, just like references.

**Comment by rando2** [comment]
Spell checker is in progress (see linked PRs)
For style, because we have such a wide range of contributors, it is quite challenging to enforce a particular style before merging in text (or at least, it slows down the process of incorporating the science, which is the priority right now). 

As a former college newspaper copy editor, my plan is just to periodically clean up sections to use consistent punctuation and other stylistic elements. It would be good to formally pick a style guide, though! I was trained on Strunk & White, so I'd be inclined to go with them.
