### ISSUE TITLE
Visibility of Preprints

### ISSUE THREAD

**Issue by matfax** [greenelab/covid19-review#272]
**Is your feature request related to a problem? Please describe.**
The preprint status of referenced papers doesn't seem to be part of the reviewing matrix. It's not clearly visible which paper is a preprint in GitHub, but preprints might need more thorough reviewing.

**Describe the solution you'd like**
Add the preprint status to the templates so that it becomes clearly visible which paper is a preprint and which already has been peer-reviewed.

**Describe alternatives you've considered**
It might also be added to the contribution methodology in that preprints are required to be stated as such in their titles.

**Additional context**
Reviewing requirements for preprints might also be extended to a minimum of two reviews for a preprint to be mentioned in the draft. A greater consensus in corner cases supports the overall significance of this project.

**Comment by rdvelazquez** [comment]
Hi @matfax I think this is an important topic to discuss; thanks for opening this issue! 

Some additional background:
- We are tracking pre-prints that don't have new paper issues here: https://github.com/greenelab/covid19-review/issues/227
- @rando2 and I discussed triaging papers for review here (and the discussion continued below): https://github.com/greenelab/covid19-review/issues/172#issuecomment-611109049 

Other things to keep in mind:
- Github provides labels to help organize issues. We could add a pre-print label.
- Only 6 of the 77 "New Paper" issues have the "More Reviews Welcome" label (indicating they have had two or more reviews). We should consider if it's worth noting which papers have _no_ reviews as it may be more important to prioritize getting at least one review for each paper than getting additional reviews for papers that already have one.

**Comment by rando2** [comment]
@rdvelazquez I agree with everything here!

One thing to note, it should be fairly straightforward to add check boxes (perhaps for "New Peer-Reviewed Paper", "Pre-print", and "Peer-Reviewed Paper (2019 & earlier)" that automatically generate the appropriate labels, like what @cgreene did for the subject areas: #25 #26 #28 

If we go this route, I would suggest splitting peer-reviewed papers into 2020 vs previous years because many of the peer-reviewed papers I've read for this project have some serious design flaws (and very short turnarounds between submission and publication).
 
I am less sure how to automatically track how many reviews an individual paper has (since it's not as simple as counting the number of comments) but I try to go through ~1 once per week and check which issues have gotten new comments.

For several of the papers that have two reviews, it's because someone added content to the manuscript that made me suspicious of the original paper and I went back through and wrote a summary to go along with my critical examination. If we had other people willing to do this, it would be super helpful, but it's a lot of work so I understand why it hasn't been happening as often! 

I'm going to tag @nafisajadavji, who is a professor involved in the awesome HCQ team, which was the best collaborative section I've seen so far. Hoping she might have some ideas for how to inspire more of that! (Working groups? Set up slack with "Birds of a Feather" style channels?)

**Comment by matfax** [comment]
I'm glad you already thought about this. I think editing the GitHub issues templates so that they also reflect options to classify the review status would be straight-forward. The GitHub bot could then add the _pre-print_ label right away. If a cross-checking mechanism should be introduced later, the bot could also manage the review labels, e.g. remove _preprint_ and add _published_ or whatever external peer-review made out of it.

Theoretically, it is also possible to check the referenced link if it ends on a preprint channel but this might not be worth the effort. Alternatively, the issue author could also be advised to only add direct links and no DOI links for preprints. That would be simple to verify for a bot by pattern matching.

**Comment by nafisajadavji** [comment]
Hi Everyone, Thanks for the tag @rando2,  I have been thinking about collaborations and how to promote them here. I haven't done anything special (e.g. reach out to anyone, set up a Slack group, etc). I did start reviewing papers and some people contributed to the review. I also contributed to others work. I am not sure if that is helpful or not.

**Comment by matfax** [comment]
#295 looks fine. Good work!
