### ISSUE TITLE
Broken citations

### ISSUE THREAD

**Issue by agitter** [greenelab/covid19-review#682]
The [build log](https://github.com/greenelab/covid19-review/runs/1374429899) for 24da920c66a20b3970440174070a8beee0e5301e shows warnings and errors for the following citations:
- doi:10.1093/pcmedi/pbaa032/5901532
- doi:10.2307/26061262
- doi:10.23812/20-editorial_1-5
- doi:10.2807/1560-7917
- doi:10.4415/ann_13_02_03
- https://act.nationalnursesunited.org/page
- https://mronline.org/wp-content/uploads/2020/06/2020-04-Frontline-Workers.pdf
- https://www.cdc.gov/about/advisory/pdf/VentDocument_Release.pdf
- https://www.census.gov/content/dam/Census/library/publications/2019/demo/p60-267.pdf
- https://www.issuelab.org/resources/695/695.pdf
- https://www.physicianscientists.org/page/summer-research-pilot-program
- https://www.synairgen.com/wp-content/uploads/2020/03/200318-Synairgen-to-start-trial-of-SNG001-in-COVID-19-imminently
- https://www.synairgen.com/wp-content/uploads/2020/07/200720-Synairgen-announces-positive-results-from-trial-of-SNG001-in-hospitalised-COVID-19-patients.pdf
- https://www.who.int/publications/i/item/report-of-the-who-china-joint-mission-on-coronavirus-disease-2019

Searching the HTML manuscript for "???" can help us find many of them.

**Comment by agitter** [comment]
doi:10.2807/1560-7917 appears to be a partial DOI from Eurosurveillance.  It was added in #635.  @rando2 do you know which paper it refers to?

doi:10.2307/26061262 is not a valid DOI, but I'm not sure where it was originally added.  It was moved out of 08.transmission.md in #659.

I'm less concerned about the URL references.  They don't have nice metadata in the reference list, and a couple have nonsense, but they provide the correct URL:
![image](https://user-images.githubusercontent.com/3532898/98725987-7d881b00-235b-11eb-9555-c8b643b1c212.png)

**Comment by rando2** [comment]
Thank you so much @agitter! Both of those were me. The second one (10.2307/26061262) was a review article by Robert Sapolsky about chronic stress & poverty -- I don't 100% remember which one I was trying to cite because he has written a lot on this topic, but I was aiming just to give people a high-level, general primer to check out if they want to learn more about a well-studied topic, so the reference that I have swapped it for should work regardless of whether it was the original intent!

I am having some residual vision problems today due to an ongoing issue with migraines, so please don't be surprised if something isn't quite right -- it's a little tricky to tell commas and periods apart right now, for example, but I tried my best to make sure they were right!

**Comment by agitter** [comment]
Oh no, sorry to hear about your vision and migraine problems.  Thanks for updating the pull request.  We can work to merge that and leave this issue open until I manually add metadata for the URLs post-submission.

**Comment by agitter** [comment]
There are a few URL references that do not have any metadata besides the URL
- https://eur-lex.europa.eu/legal-content/EN/ALL
- https://eur-lex.europa.eu/legal-content/EN/TXT
- https://cen.acs.org/biological-chemistry/natural-products/oleandrin-compound-touted-possible-COVID/98/web/2020/08

Now that we're caching reference metadata as of #847, we'll have to remove those references from `content/manual-references-2021-02-08.json` if we add correct manual metadata for them.

**Comment by rando2** [comment]
I'm not seeing the eur-lex links in the manual references, but we probably want to add them there - it seems like there's important info after the `?` in the url.

https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=celex%3A32002L0046
https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32004L0027

@cgreene wants to keep an eye on #847 yet since it only improved the build time by 3 minutes during its initial build.

**Comment by agitter** [comment]
Here are the locations of those URL references to help us follow up on them later:
- https://greenelab.github.io/covid19-review/v/6cfa2d74054751ca0896944d4ffaf802c68391bd/#ref-CWdgoTUe
- https://greenelab.github.io/covid19-review/v/6cfa2d74054751ca0896944d4ffaf802c68391bd/#ref-G7TnkK6t
- https://greenelab.github.io/covid19-review/v/6cfa2d74054751ca0896944d4ffaf802c68391bd/#ref-Ssmsdskt

**Comment by agitter** [comment]
Closing this because the latest builds are clean
