### ISSUE TITLE
"6.2.4 Access to and Representation in Clinical Trials" is blank

### ISSUE THREAD

**Issue by rdvelazquez** [greenelab/covid19-review#684]
**Is your feature request related to a problem? Please describe.**
Section `6.2.4 Access to and Representation in Clinical Trials` is currently blank

<img width="1001" alt="Screen Shot 2020-11-10 at 11 56 09 AM" src="https://user-images.githubusercontent.com/25244432/98705463-bd470680-234b-11eb-935b-9b004b03d083.png">

**Describe the solution you'd like**
Either write this section or remove the header (with submission planned soon, removing it for now may make more sense)

**Comment by agitter** [comment]
#600 adds this section.  @rando2 is that scheduled to be merged before the first submission?

I now see that #600 also adds one of the missing images I mentioned in #673.

**Comment by rando2** [comment]
@agitter I will double-check with @tlukan what his plans are, since it's originally his text. He submitted the original version in August and it took me a while to learn enough to try to provide feedback. He's a sophomore and I imagine having a very weird semester right now so I'm not sure what will work best for him :(

If he needs more time, we can just stick a summary sentence about this issue to the end of the section above and then add this in at a later time.

**Comment by rando2** [comment]
@tlukan and I discussed and he has approved the changes! I'll ask Casey to give it a once-over before I merge it in, unless someone else is willing to!
