### ISSUE TITLE
Managing References for Sections Separately

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#732]
**Is your feature request related to a problem? Please describe.**
We are splitting the manuscript into pieces that will be submitted separately to _mSystems_ for the version of record, but it will be a lot easier to manage the project if we can keep everything centralized in a single repository. Additionally, since the content of the repository will be continuously updated, it would be great to keep the pdf and html versions here pretty similar to what they are now (a single document per the typical Manubot workflow).

However, it would be great if there might be a way to generate separate reference lists for each section solely for the purposes of submission -- perhaps in the docx output?

**Describe the solution you'd like**
An option to compile reference lists separately for each .md file in content (and to output a docx file)

**Describe alternatives you've considered**
The way to do this using only native Manubot features would be to set up separate Manubot repositories for each manuscript that will be submitted. The pro is that this would make some aspects a little easier (like generating separate title pages for each), but it would significantly complicate collaboration.

**Additional context**
Also open to other alternatives if anyone has any creative ideas!
It would be great to see what @agitter and @vincerubinetti think (per @cgreene's suggestion!)

**Comment by agitter** [comment]
We may not have much control over this because reference placement is managed by Pandoc and citeproc (formerly pandoc-citeproc).  A [2018 post](https://groups.google.com/u/1/g/pandoc-discuss/c/N4Hmr8wErBs) gives some clues about this.  The Pandoc creator said it is not possible (as of 2018), and the Pandoc lua filter linked there is not maintained. @dhimmel is the expert here and can correct me.

_If_ the above is true, I think we should run Manubot/Pandoc once per individual manuscript to get the reference numbers correct.  That doesn't seem terribly difficult to me if we do it in an ad hoc way.  We can customize the `build.sh` script to run Pandoc on subsets of content files, all within this repository.

I'd have to look at the `manubot webpage` command again to see what options we have for deployment.  Two options could be:
1) Modify the `deploy.sh` script to deploy all 6 individual manuscripts as https://greenelab.github.io/covid19-review/overview.html, https://greenelab.github.io/covid19-review/diagnostics, etc.
2) Build the merged manuscript in addition to the individual manuscripts, deploy only the merged manuscript, and get the individual manuscripts from the CI artifacts or `output` branch as needed.  This seems to be what @rando2 and @cgreene prefer.  I'm starting to prefer this as well.

Building all the individual manuscripts and the merged manuscript each time could make the builds really slow.  If we are going to do both of those, we could toggle the individual manuscript builds with an environment variable.  We could also only build the docx version.

**Comment by dhimmel** [comment]
Noting https://github.com/jgm/citeproc/issues/5 for any updates on multiple reference section support in Pandoc.

> Build the merged manuscript in addition to the individual manuscripts, deploy only the merged manuscript, and get the individual manuscripts from the CI artifacts or output branch as needed.

This seems like a good solution to me. If you can script the creation of the individual submission manuscripts, that's great. You could rerun for the initial submissions and any resubmissions.

**Comment by rando2** [comment]
Thank you so much @agitter and @dhimmel. I think it would be totally find not to run the individual builds until we wanted a final version. @cgreene was keen to keep the online version pretty consistent with its current format and to just build the separate documents for submission, so this sounds like a great solution to me.

**Comment by agitter** [comment]
Closed by #763
