### ISSUE TITLE
Notes on the Pathogenesis manuscript

### ISSUE THREAD

**Issue by lubianat** [greenelab/covid19-review#782]
Hello all, sharing  a few points to discuss with you:

1. SARS-CoV-2 has a high affinity for the human ACE2 receptor, which is expressed in the vascular epithelium, other epithelial cells, and cardiovascular and renal tissues [59,60].

- ACE2 is actually expressed in many other tissues.  There are specific reviews on that, ex: https://www.embopress.org/doi/full/10.15252/msb.20209610. Should I review this paper and update the citation?

2. The ACE2 receptor is expressed in numerous organs, such as the heart, kidney, and intestine, but it is most prominently expressed in alveolar epithelial cells; this pattern of expression is expected to contribute to the virus’ association with lung pathology [59,77].

- Ref. 77 seems to be only tangentially related, while ref 59 is from March (much ACE2 work since then!). 

3. No comprehensive proteomic analyses of the pathogen or of patients suffering from its infection have yet been reported.

- Outdated. Ex: Ultra-High-Throughput Clinical Proteomics Reveals Classifiers of COVID-19 Infection

https://www.sciencedirect.com/science/article/pii/S2405471220301976

4. The variability of both which symptoms present and their severity

- This phrase appears 3 times in the text exactly like that and the sentences only slightly differ. It looks like internal copy.

Section 1.3.2: The variability of both which symptoms present and their severity makes it difficult for public health agencies to provide clear recommendations for citizens regarding what symptoms indicate SARS-CoV-2 infection and should prompt isolation.

Section 2.5: The variability of both which symptoms present and their severity has presented challenges for public health agencies to provide clear recommendations for citizens regarding what symptoms indicate SARS-CoV-2 infection and should prompt isolation.

Section 2.11: The variability of both which symptoms present and their severity have presented challenges for public health agencies seeking to provide clear recommendations regarding which symptoms indicate SARS-CoV-2 infection and should prompt isolation.

Is there a way to test for "internal" plagiarism?

**Comment by agitter** [comment]
> No comprehensive proteomic analyses of the pathogen or of patients suffering from its infection have yet been reported.
Outdated.

I agreed with this.  In my proofreading (#783) I deleted that sentence.  There are a few comprehensive proteomics studies now.  Because this version is so close to submission and we plan to submit an updated version or multiple updates, I propose we save expanding the proteomics discussion for the next version.

**Comment by rando2** [comment]
Hi @lubianat, Thank you for this feedback!

1. I opened PR #794 to add a reference to the link you included -- please feel free to propose alternative changes as you see fit!
2. I opened #795 to add a couple references-- I'm not sure if this addresses your concerns or if there is additional content that we are missing? This isn't an area I know super well.
3. We need to update that section (I imagine as soon as we finish the submission) -- I believe @bansalvi has several ideas!
4. The repeat in 1.3.2 I'm not worried about -- we will eventually delete the Introduction, because it's a holdover from the old, book-like format. Right now I've left it up because I'm making sure everything we need from it is redistributed to the individual papers. The duplication within Pathogenesis is addressed in #796. Some sort of internal plagarism checker would be amazing, though, since I have moved sooo much text around that it's sometimes hard to be confident where it ended up (I was quite sure I already deleted that first appearance, since I didn't like it in that paragraph!)
